---
- name: Installing mysql 
  apt:
    update_cache: yes
    name: mysql-server
    state: present
- name: Install python3-PyMySQL library
  apt:
    name: python3-pymysql
    state: present
- name: update mysql root password for root account
  mysql_user:
    name: "{{ mysql_user }}"
    login_unix_socket: "{{ login_socket }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    host: 'localhost'
    password: "{{ mysql_password }}"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
    state: present