---
- name: Add Nodesource apt key.
  apt_key:
    url: "{{node_key}}"
    id: "{{key_id}}"
    state: present
- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb {{ node_repository }} {{ ansible_distribution_release }} main"
    - "deb-src {{ node_repository }} {{ ansible_distribution_release }} main"
  register: node_repo
- name: Update apt cache if repo was added.
  apt: 
    update_cache: yes
  when: node_repo.changed
  tags: ['skip_ansible_lint']
- name: Installing NodeJs
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{nodejs_packages}}"
- name: Installing npm 
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items: "{{ npm_dependencies }}"