---
- name: Installing Spurt Commerce
  hosts: all
  become: yes
  tasks:
    - name: Installing Apache2
      apt:
        name: apache2
        state: present
    - name: Enabling a2enmod
      apache2_module: 
        name: "{{item}}"
        state: present
      with_items:
        - proxy 
        - proxy_http
        - headers
    - name: started Apache2
      systemd:
        name: apache2
        state: started
    - name: Setting reverse proxy
      template:
        src: '000-default.conf.j2'
        dest: /etc/apache2/sites-available/000-default.conf
      notify:
        - daemon-reload and restart apache2
  handlers:
    - name: daemon-reload and restart apache2
      systemd:
        name: apache2
        daemon-reload: yes
        state: restarted